-- =====================================================================
-- HDJ Vérif — thésaurus des synonymes de la recherche
--
-- OBJET
--   Une recherche par mots-clés ne trouve rien quand l'usager écrit autre chose que
--   le libellé officiel : « scanner » pour une « scanographie », « IRM » pour une
--   « remnographie », « anti-TNF » pour de l'« infliximab ». Ce fichier installe le
--   **thésaurus** qui élargit la requête, et rebranche dessus les deux recherches de
--   l'application (`rechercher_ccam`, `rechercher_medicaments`).
--
-- SOURCE DE VÉRITÉ
--   `data/thesaurus-synonymes.csv`, chargé par `scripts/import-referentiels.mjs`.
--   Le fichier est **la** référence : le SQL ne fait que le rejouer et l'interroger.
--   Les correspondances ne sont donc pas écrites ici (à une exception près, les mots
--   vides, qui doivent rester alignés sur `MOTS_VIDES` de `scripts/lib/thesaurus.mjs`).
--
-- MODÈLE
--   notion   : concept pivot (« tomodensitométrie ») ; ses termes sont synonymes
--   terme    : mot ou expression tel qu'on l'écrit (affiché à l'usager)
--   terme_normalise : clé de comparaison (minuscules, sans accent), calculée à l'import
--   domaine  : actes | medicaments | commun
--
-- À APPLIQUER APRÈS `rpc-recherche.sql` ET `ccam-arbres.sql` :
--   il REDÉFINIT `rechercher_ccam` et `rechercher_medicaments` pour y brancher le
--   thésaurus (les deux précédents fichiers restent la description du modèle).
--     psql < supabase/thesaurus.sql
--     node scripts/appliquer-sql.mjs supabase/thesaurus.sql --verifier
-- =====================================================================

create extension if not exists unaccent;
create extension if not exists pg_trgm;

-- ---------------------------------------------------------------------
-- 1. Normalisation (partagée par le thésaurus et les requêtes)
-- ---------------------------------------------------------------------

-- Doit rester **identique** à `normaliserTerme()` de `scripts/lib/thesaurus.mjs` :
-- minuscules, ligatures dépliées, accents retirés, tout séparateur ramené à une espace.
-- (STABLE, et non IMMUTABLE : `unaccent()` l'est lui-même. Aucun index ne s'appuie donc
--  sur cette fonction — les colonnes normalisées sont calculées à l'import.)
create or replace function public.normaliser_terme(p_texte text)
returns text
language sql
stable
set search_path = public, extensions, pg_catalog
as $$
  select nullif(
    btrim(
      regexp_replace(
        lower(unaccent(replace(replace(coalesce(p_texte, ''), 'œ', 'oe'), 'æ', 'ae'))),
        '[^a-z0-9]+', ' ', 'g'
      )
    ),
    ''
  );
$$;

comment on function public.normaliser_terme(text) is
  'Forme normalisée d''un terme de recherche : minuscules, sans accent ni ligature, séparateurs ramenés à une espace. Alignée sur normaliserTerme() du thésaurus.';

-- ---------------------------------------------------------------------
-- 2. Table du thésaurus
-- ---------------------------------------------------------------------
create table if not exists public.thesaurus_synonymes (
  id              bigint generated by default as identity primary key,
  notion          text not null,
  terme           text not null,
  terme_normalise text not null,
  type            text,
  domaine         text not null default 'commun'
                  check (domaine in ('actes', 'medicaments', 'commun')),
  source          text,
  unique (notion, terme_normalise)
);

comment on table public.thesaurus_synonymes is
  'Thésaurus des synonymes de la recherche (source : data/thesaurus-synonymes.csv). Deux termes de la même notion sont synonymes : chercher l''un trouve l''autre.';
comment on column public.thesaurus_synonymes.notion is
  'Concept pivot, en clair — jamais affiché : il ne sert qu''à rapprocher les termes.';
comment on column public.thesaurus_synonymes.terme_normalise is
  'Clé de comparaison (minuscules, sans accent), calculée à l''import — voir normaliser_terme().';
comment on column public.thesaurus_synonymes.domaine is
  'actes (nomenclature CCAM), medicaments (BDPM) ou commun.';

create index if not exists idx_thesaurus_terme
  on public.thesaurus_synonymes (terme_normalise);

create index if not exists idx_thesaurus_notion
  on public.thesaurus_synonymes (notion);

-- ---------------------------------------------------------------------
-- 3. Lecture publique, écriture interdite depuis le navigateur
-- ---------------------------------------------------------------------
alter table public.thesaurus_synonymes enable row level security;
alter table public.thesaurus_synonymes force row level security;

drop policy if exists "lecture publique du thesaurus" on public.thesaurus_synonymes;
create policy "lecture publique du thesaurus"
  on public.thesaurus_synonymes
  for select
  to anon, authenticated
  using (true);

revoke all on public.thesaurus_synonymes from anon, authenticated;
grant select on public.thesaurus_synonymes to anon, authenticated;

-- ---------------------------------------------------------------------
-- 4. Mots vides
--
--    Jamais interrogés seuls : sans cette liste, une requête comme « prothèse **de**
--    hanche » ramènerait tout acte contenant « de ». À maintenir à l'identique de
--    `MOTS_VIDES` (scripts/lib/thesaurus.mjs) — les tests comparent les deux.
-- ---------------------------------------------------------------------
create or replace function public.mots_vides_recherche()
returns text[]
language sql
immutable
as $$
  select array[
    'au', 'aux', 'avec', 'dans', 'de', 'des', 'du', 'elle', 'en', 'et',
    'la', 'le', 'les', 'ou', 'par', 'pour', 'sans', 'sur', 'un', 'une'
  ];
$$;

comment on function public.mots_vides_recherche() is
  'Mots vides exclus du découpage d''une requête (alignés sur MOTS_VIDES de scripts/lib/thesaurus.mjs).';

-- ---------------------------------------------------------------------
-- 5. Rapprochement d'un terme à un texte
--
--    `p_texte` est la colonne `recherche_normalisee` : déjà normalisée (minuscules, sans
--    accent) et **encadrée d'espaces**, calculée par l'import (voir `scripts/lib/referentiels.mjs`).
--    Rien n'est donc normalisé à la frappe, et les deux formes sont indexables en trigrammes.
--
--    Un **sigle** (IRM, ECG, AVC, TDM… : quatre caractères ou moins, sans espace) se cherche
--    comme **mot entier** — sinon « AIT » se reconnaîtrait dans « traitement ». Les autres
--    termes se cherchent par inclusion (« radio » trouve « radiographie »).
--    Les termes étant normalisés, ils ne contiennent aucun métacaractère : l'interpolation
--    `like` est sans risque.
-- ---------------------------------------------------------------------
create or replace function public.thesaurus_contient(p_texte text, p_terme text)
returns boolean
language sql
immutable
as $$
  select case
    when p_texte is null or p_terme is null or p_terme = '' then false
    when length(p_terme) <= 4 and position(' ' in p_terme) = 0
      then p_texte like '% ' || p_terme || ' %'
    else p_texte like '%' || p_terme || '%'
  end;
$$;

comment on function public.thesaurus_contient(text, text) is
  'Vrai si le texte de recherche (normalisé, encadré d''espaces) porte le terme : mot entier pour un sigle (≤ 4 caractères), inclusion sinon. Aligné sur contientTerme() du thésaurus.';

-- ---------------------------------------------------------------------
-- 6. Découpage d'une saisie et élargissement
--
--    `thesaurus_saisie` rend les termes *écrits* par l'usager : la saisie entière, et
--    — seulement si elle n'est pas elle-même un terme du thésaurus — ses mots (hors
--    mots vides). Cette restriction est ce qui évite le faux ami : « anti-TNF » se
--    cherche comme un tout, et non mot à mot (« anti » ramènerait
--    l'anti-lymphocytaire, l'anti-inflammatoire, l'anti-arythmique…).
--
--    `thesaurus_requete` y ajoute les synonymes des notions atteintes : c'est le
--    thésaurus proprement dit.
-- ---------------------------------------------------------------------
create or replace function public.thesaurus_saisie(p_terme text)
returns text[]
language sql
stable
set search_path = public, extensions, pg_catalog
as $$
  with saisie as (
    select public.normaliser_terme(p_terme) as t
  ),
  phrase as (
    select t as terme
    from saisie
    where t is not null
      and not (t = any (public.mots_vides_recherche()))
  ),
  connue as (
    select exists (
      select 1
      from public.thesaurus_synonymes s
      join phrase p on p.terme = s.terme_normalise
    ) as oui
  ),
  mots as (
    select distinct mot
    from saisie, regexp_split_to_table(saisie.t, ' ') as mot
    where length(mot) >= 2
      and not (mot = any (public.mots_vides_recherche()))
      -- Un mot court n'est interrogé que s'il est **lui-même un terme du thésaurus**
      -- (« IRM », « AVC », « rein ») : « anti » découpé de « anti-TNF » ramènerait tout
      -- ce qui contient ce mot (immunoglobuline anti-lymphocytaire, anti-inflammatoire…).
      -- Seuil 5, repris tel quel de LONGUEUR_MOT_SIGNIFICATIF (scripts/lib/thesaurus.mjs).
      and (
        length(mot) >= 5
        or exists (
          select 1 from public.thesaurus_synonymes s where s.terme_normalise = mot
        )
      )
  )
  select coalesce(array_agg(distinct terme), '{}')
  from (
    select terme from phrase
    union
    -- Saisie reconnue comme une **notion entière** (« anti-TNF », « prothèse de hanche »,
    -- « fer injectable ») : ses mots ne sont pas interrogés séparément, sinon
    -- « prothèse » ou « injectable » ramèneraient tout ce qui les contient.
    select mot from mots where not (select oui from connue)
  ) x;
$$;

comment on function public.thesaurus_saisie(text) is
  'Termes écrits par l''usager : la saisie entière, et ses mots (hors mots vides) seulement si la saisie n''est pas elle-même un terme du thésaurus.';

create or replace function public.thesaurus_requete(
  p_terme   text,
  p_domaine text default null
)
returns text[]
language sql
stable
set search_path = public, extensions, pg_catalog
as $$
  with ecrits as materialized (
    select unnest(public.thesaurus_saisie(p_terme)) as terme
  ),
  notions as materialized (
    select distinct s.notion
    from public.thesaurus_synonymes s
    join ecrits e on e.terme = s.terme_normalise
    where p_domaine is null or s.domaine in ('commun', p_domaine)
  )
  select coalesce(array_agg(distinct terme), '{}')
  from (
    select terme from ecrits
    union
    select s.terme_normalise
    from public.thesaurus_synonymes s
    join notions n on n.notion = s.notion
    where p_domaine is null or s.domaine in ('commun', p_domaine)
  ) x;
$$;

comment on function public.thesaurus_requete(text, text) is
  'Termes à interroger pour une saisie : la saisie (et ses mots), puis les synonymes des notions atteintes.';

-- ---------------------------------------------------------------------
-- 7. Synonymes lisibles d'une saisie (affichage : « recherche élargie à… »)
-- ---------------------------------------------------------------------
create or replace function public.synonymes_de(
  p_terme   text,
  p_domaine text default null,
  p_limite  integer default 12
)
returns table (
  terme            text,
  terme_normalise  text,
  notion           text,
  type             text,
  domaine          text
)
language sql
stable
security invoker
set search_path = public, extensions, pg_catalog
as $$
  with ecrits as materialized (
    select unnest(public.thesaurus_saisie(p_terme)) as terme
  ),
  notions as materialized (
    select distinct s.notion
    from public.thesaurus_synonymes s
    join ecrits e on e.terme = s.terme_normalise
    where p_domaine is null or s.domaine in ('commun', p_domaine)
  )
  select s.terme, s.terme_normalise, s.notion, s.type, s.domaine
  from public.thesaurus_synonymes s
  join notions n on n.notion = s.notion
  where (p_domaine is null or s.domaine in ('commun', p_domaine))
    and s.terme_normalise not in (select terme from ecrits)
  order by s.notion, s.terme
  limit greatest(1, least(coalesce(p_limite, 12), 40));
$$;

comment on function public.synonymes_de(text, text, integer) is
  'Synonymes lisibles des notions atteintes par une saisie, hors termes déjà écrits — affichés sous le champ de recherche.';

-- ---------------------------------------------------------------------
-- 8. Colonne de recherche normalisée des deux référentiels
--
--    La normalisation (accents, ligatures, séparateurs) coûtait un `unaccent()` **par
--    ligne et par frappe**. Elle est désormais payée une fois, à l'import, et stockée :
--    `recherche_normalisee` porte le libellé, les mots-clés et le code, normalisés et
--    encadrés d'espaces (l'espace de tête permet de reconnaître un sigle comme mot
--    entier, et un libellé qui *commence* par la saisie).
--
--    ⚠️ Cette colonne est remplie par `scripts/import-referentiels.mjs` : un référentiel
--    importé par une version antérieure du script la laisse vide, et la recherche ne
--    trouverait alors rien. `scripts/verifier-referentiel.mjs` le contrôle.
-- ---------------------------------------------------------------------
alter table public.referentiel_ccam
  add column if not exists recherche_normalisee text;

alter table public.referentiel_medicaments
  add column if not exists recherche_normalisee text;

-- Le **libellé seul**, pour classer : les mots-clés d'un acte réunissent tous les synonymes
-- de ses notions, si bien qu'ils ne distinguent plus « prothèse totale de hanche » de
-- « hanche ». Le classement s'appuie donc sur le libellé, réservant les mots-clés au rappel.
alter table public.referentiel_ccam
  add column if not exists libelle_normalisee text;

comment on column public.referentiel_ccam.libelle_normalisee is
  'Libellé de l''acte seul, normalisé et encadré d''espaces : sert au classement des résultats (le rappel s''appuie sur recherche_normalisee).';

comment on column public.referentiel_ccam.recherche_normalisee is
  'Texte de recherche de l''acte : libellé, mots-clés (arborescence et thésaurus) et code, normalisés et encadrés d''espaces. Colonne interrogée par rechercher_ccam (index trigramme).';
comment on column public.referentiel_medicaments.recherche_normalisee is
  'Texte de recherche de la spécialité : dénomination et DCI, normalisées et encadrées d''espaces. Colonne interrogée par rechercher_medicaments (index trigramme).';

create index if not exists idx_ccam_recherche_trgm
  on public.referentiel_ccam using gin (recherche_normalisee gin_trgm_ops);

create index if not exists idx_medicaments_recherche_trgm
  on public.referentiel_medicaments using gin (recherche_normalisee gin_trgm_ops);

-- ---------------------------------------------------------------------
-- 9. Recherche des actes CCAM, élargie au thésaurus
--
--    Trois étages, du plus précis au plus large :
--      1. code exact, puis préfixe de code (saisie d'un code connu) ;
--      2. libellé de la nomenclature commençant par la saisie ;
--      3. **mots-clés** (libellé, arborescence, thésaurus) et vocabulaire étendu.
--
--    Le classement privilégie le nombre de mots de la requête reconnus : « prothese
--    hanche » remonte d'abord les actes qui portent les deux mots.
--    NB : `ccam-arbres.sql` définissait la version précédente ; celle-ci la remplace.
-- ---------------------------------------------------------------------
drop function if exists public.rechercher_ccam(text, integer);

create function public.rechercher_ccam(
  p_terme  text,
  p_limite integer default 12
)
returns table (
  code                    varchar(255),
  libelle                 text,
  acte_marqueur_hdj       boolean,
  exclusif_externe        boolean,
  necessite_plateau_lourd boolean,
  acte_classant           boolean,
  eligibilite_hdj         text,
  motif_eligibilite_hdj   text,
  type_acte               text,
  racines_ghm             text
)
language sql
stable
security invoker
set search_path = public, extensions, pg_catalog
as $$
  with cible as materialized (
    select public.normaliser_terme(p_terme) as t
  ),
  ecrits as materialized (
    select unnest(public.thesaurus_saisie(p_terme)) as terme
  ),
  termes as materialized (
    select distinct terme
    from unnest(public.thesaurus_requete(p_terme, 'actes')) as terme
    where terme is not null
      and not (terme = any (public.mots_vides_recherche()))
  ),
  scores as (
    select
      a.code, a.libelle, a.acte_marqueur_hdj, a.exclusif_externe,
      a.necessite_plateau_lourd, a.acte_classant, a.eligibilite_hdj,
      a.motif_eligibilite_hdj, a.type_acte, a.racines_ghm,
      a.recherche_normalisee as meule,
      a.libelle_normalisee as libelle_seul,
      -- Deux scores sur le **libellé** (et non sur les mots-clés, qui réunissent tous les
      -- synonymes d'un acte et ne distinguent donc plus rien) : les mots **écrits** par
      -- l'usager d'abord, puis le synonyme le plus spécifique reconnu — « prothèse totale
      -- de hanche » (4 mots) passe ainsi devant « hanche » (1 mot) pour une saisie
      -- « prothèse de hanche ». Le score sur le texte complet sert de rappel.
      (select count(*) from ecrits e
        where public.thesaurus_contient(a.libelle_normalisee, e.terme)) as mots_ecrits,
      (select coalesce(max(array_length(string_to_array(t.terme, ' '), 1)), 0)
        from termes t
        where public.thesaurus_contient(a.libelle_normalisee, t.terme)) as precision_libelle,
      (select count(*) from termes t
        where public.thesaurus_contient(a.recherche_normalisee, t.terme)) as mots_reconnus
    from public.referentiel_ccam a, cible
    where cible.t is not null
      and (
        lower(a.code) = lower(cible.t)
        -- Préfixe de code à partir de trois caractères : les codes CCAM en comptent sept,
        -- et « de » ou « du » ne doivent pas ramener tout un chapitre.
        or (length(cible.t) >= 3 and lower(a.code) like lower(cible.t) || '%')
        or exists (
          select 1 from termes t
          where public.thesaurus_contient(a.recherche_normalisee, t.terme)
        )
      )
  )
  select
    code, libelle, acte_marqueur_hdj, exclusif_externe, necessite_plateau_lourd,
    acte_classant, eligibilite_hdj, motif_eligibilite_hdj, type_acte, racines_ghm
  from scores, cible
  order by
    -- 1. code exact · 2. préfixe de code (≥ 3 caractères) ·
    -- 3. libellé commençant par la saisie (mot entier) · 4. saisie reconnue comme mot du
    -- libellé · 5. complément de mot dans le libellé (« endoscop ») · 6. saisie reconnue
    -- dans les mots-clés (rapprochement par synonyme) ·
    -- 7. mots **écrits** par l'usager reconnus dans le libellé · 8. synonyme le plus
    -- spécifique reconnu dans le libellé · 9. nombre de synonymes reconnus ·
    -- 10. saisie le plus tôt possible · 11. libellé le plus court, puis code.
    (lower(code) = lower(cible.t)) desc,
    (length(cible.t) >= 3 and lower(code) like lower(cible.t) || '%') desc,
    (libelle_seul like ' ' || cible.t || ' %') desc,
    (libelle_seul like '% ' || cible.t || ' %') desc,
    (libelle_seul like ' ' || cible.t || '%' or libelle_seul like '% ' || cible.t || '%') desc,
    (meule like '% ' || cible.t || ' %') desc,
    mots_ecrits desc,
    precision_libelle desc,
    mots_reconnus desc,
    position(cible.t in libelle_seul),
    length(libelle),
    code
  limit greatest(1, least(coalesce(p_limite, 12), 100));
$$;

-- ---------------------------------------------------------------------
-- 10. Recherche des médicaments, élargie au thésaurus
--
--     La dénomination et la DCI forment le texte de recherche ; le thésaurus apporte les
--     classes (« anti-TNF » → infliximab, adalimumab…), les sigles et les noms d'usage.
-- ---------------------------------------------------------------------
drop function if exists public.rechercher_medicaments(text, integer);

create function public.rechercher_medicaments(
  p_terme  text,
  p_limite integer default 12
)
returns table (
  cis                    varchar(255),
  denomination           text,
  dci                    text,
  est_reserve_hospitaliere boolean,
  est_liste_en_sus       boolean,
  surveillance_particuliere boolean,
  surveillance_renforcee boolean
)
language sql
stable
security invoker
set search_path = public, extensions, pg_catalog
as $$
  with cible as materialized (
    select public.normaliser_terme(p_terme) as t
  ),
  ecrits as materialized (
    select unnest(public.thesaurus_saisie(p_terme)) as terme
  ),
  termes as materialized (
    select distinct terme
    from unnest(public.thesaurus_requete(p_terme, 'medicaments')) as terme
    where terme is not null
      and not (terme = any (public.mots_vides_recherche()))
  ),
  scores as (
    select
      m.cis, m.denomination, m.dci, m.est_reserve_hospitaliere, m.est_liste_en_sus,
      m.surveillance_particuliere, m.surveillance_renforcee,
      m.recherche_normalisee as meule,
      (select count(*) from ecrits e
        where public.thesaurus_contient(m.recherche_normalisee, e.terme)) as mots_ecrits,
      (select count(*) from termes t
        where public.thesaurus_contient(m.recherche_normalisee, t.terme)) as mots_reconnus,
      (select coalesce(max(array_length(string_to_array(t.terme, ' '), 1)), 0)
        from termes t
        where public.thesaurus_contient(m.recherche_normalisee, t.terme)) as precision_synonyme
    from public.referentiel_medicaments m, cible
    where cible.t is not null
      and exists (
        select 1 from termes t
        where public.thesaurus_contient(m.recherche_normalisee, t.terme)
      )
  )
  select
    cis, denomination, dci,
    est_reserve_hospitaliere, est_liste_en_sus, surveillance_particuliere, surveillance_renforcee
  from scores, cible
  order by
    -- 1. saisie = premier mot · 2. saisie reconnue comme mot · 3. mot commençant par la
    -- saisie · 4. nombre de mots **écrits** par l'usager reconnus · 5. synonyme le plus
    -- spécifique reconnu · 6. nombre de synonymes reconnus · 7. saisie le plus tôt
    -- possible · 8. nom le plus court.
    (meule like ' ' || cible.t || ' %') desc,
    (meule like '% ' || cible.t || ' %') desc,
    (meule like ' ' || cible.t || '%' or meule like '% ' || cible.t || '%') desc,
    mots_ecrits desc,
    precision_synonyme desc,
    mots_reconnus desc,
    position(cible.t in meule),
    length(denomination),
    denomination
  limit greatest(1, least(coalesce(p_limite, 12), 50));
$$;

-- ---------------------------------------------------------------------
-- 11. Droits d'exécution
-- ---------------------------------------------------------------------
revoke all on function public.synonymes_de(text, text, integer) from public;
revoke all on function public.rechercher_ccam(text, integer) from public;
revoke all on function public.rechercher_medicaments(text, integer) from public;

grant execute on function public.synonymes_de(text, text, integer) to anon, authenticated;
grant execute on function public.rechercher_ccam(text, integer) to anon, authenticated;
grant execute on function public.rechercher_medicaments(text, integer) to anon, authenticated;
